# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20547bbc56e66f37758f4fc5aaea8f026670293e03624c13fb08e2e5b5b7958aee938c0fc3c4268d793679ede7150eee618097718922b8616d6ca583dacb171c

test:
  secret_key_base: 016d07a79467b9b41f0753e43d34ac4f97560dcc168581b7009c8e01e176072c2813f4f257c1dcf5657a440122e0b3f8b4e204d8177e0512a53c218adee2fb16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
